x-include: &include
  project_directory: .
  env_file: .env

include:
  - <<: *include
    path: docker/compose.datastore.yaml
  - <<: *include
    path: docker/compose.ollama.yaml
  - <<: *include
    path: docker/compose.temporal.yaml
  - <<: *include
    path: docker/compose.milvus.yaml
  - <<: *include
    path: docker/compose.meilisearch.yaml

networks:
  default:
    name: local-infra
